version: "3.9"

services:
  flask_app:
    container_name: flask_app
    build: ./server
    ports:
      - "4000:4000"
    # This will map the source code from ./server on the local machine to /code inside the container
    volumes:
      - ./server:/code
    environment:
      - DB_URL=postgresql://postgres:postgres@flask_db:5432/postgres
      - DB_HOST=postgres_db
      - DB_USERNAME=postgres
      - DB_PASSWORD=postgres
      - DB_NAME=postgres
      - DB_PORT=5432
    depends_on:
      - postgres_db

  postgres_db:
    container_name: postgres_db
    image: postgres:16
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=postgres
      - PGUSER=root
    volumes:
      # Map intitialization scripts into containers
      - ./db/seeds.sql:/docker-entrypoint-initdb.d/seeds.sql
      # Persist the data
      #- pgdata:/var/lib/postgresql/data

volumes:
# pgdata is stored locally within docker. use "docker volume ls" to view all the volumes and delete one if necessary
  pgdata: {}