version: "3.9"

services:
  flask_app:
    container_name: flask_app
    build: ./server
    ports:
      - "4000:4000"
    # This will map the source code from ./server on the local machine to /code inside the container
    volumes:
      - ./server:/code
    environment:
      - DB_URL=postgresql://postgres:postgres@flask_db:5432/postgres
    depends_on:
      - flask_db
  flask_db:
    container_name: flask_db
    image: postgres:12
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=postgres
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: {}